### ISSUE TITLE
Building not successfully on ubuntu 24.04 but works on ubuntu 22.04

### ISSUE THREAD

**Issue by 1cebangbang** [google/visqol#136]
On ubuntu 24 the ERROR appears like this (The build was almost completed but paused at about 980/983):
"/_(bazelPath)_/96a4d4bb30ef4ff7145b10c5711cf728/external/org_tensorflow/tensorflow/lite/kernels/internal/BUILD:858:11: Compiling tensorflow/lite/kernels/internal/spectrogram.cc failed: (Exit 1): gcc failed: error executing command

............

# Execution platform: @local_execution_config_platform//:platform
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:46:22: error: 'uint32_t' was not declared in this scope
   46 | inline int Log2Floor(uint32_t n) {
      |                      ^~~~~~~~
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:20:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   19 | #include <math.h>
  +++ |+#include <cstdint>
   20 | 
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:61:24: error: 'uint32_t' was not declared in this scope
   61 | inline int Log2Ceiling(uint32_t n) {
      |                        ^~~~~~~~
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:61:24: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:69:8: error: 'uint32_t' does not name a type
   69 | inline uint32_t NextPowerOfTwo(uint32_t value) {
      |        ^~~~~~~~
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:69:8: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc: In member function 'bool tflite::internal::Spectrogram::Initialize(const std::vector<double>&, int)':
external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc:92:17: error: 'NextPowerOfTwo' was not declared in this scope
   92 |   fft_length_ = NextPowerOfTwo(window_length_);
      |                 ^~~~~~~~~~~~~~
Target //:visqol failed to build
INFO: Elapsed time: 6.170s, Critical Path: 4.74s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
"

but on a new installed ubuntu 22 the building completed successfully.(the ViSQOL files on both systems were only  changed on the WORKSPACE of armadillo downloading, and bazel version are both 5.3.2)
I wonder if the error occurs because of the ubuntu itself, a wrong version of the gcc (or other) compiler or the incorrect setting of the bazel.
The release now is https://github.com/google/visqol/releases/tag/v3.3.3 and thanks to developers and the Developers successfully built ViSQOL on ubuntu 24.

**Comment by jrop** [comment]
I was able to find the right combination of build dependencies to build Visqol using a Nix environment:

<details>
<summary>shell.nix</summary>

```nix
let
  # We need an older compiler and libc so that the output binary can run on
  # older systems. This particular hash was obtained by reverse-searching for
  # GLIBC 2.35:
  pkgsOld =
    import
      (fetchTarball "https://github.com/nixos/nixpkgs/tarball/56a9ace9335180b6702f039c770e561478f428db")
      { };

  # Newer generation of Python, so we can get distutils:
  pkgs = import (fetchTarball "https://github.com/nixos/nixpkgs/archive/nixos-24.11.tar.gz") { };

  # Bazel 5.3.2:
  bazel532pkgs =
    import
      (fetchTarball "https://github.com/nixos/nixpkgs/tarball/1d77a869046c119ea50837ca1f94594b64985f77")
      { };
in
{ }:
pkgs.mkShell {
  packages = [
    bazel532pkgs.bazel_5

    pkgsOld.gcc11
    pkgsOld.git
    pkgsOld.perl

    pkgs.python312
    pkgs.python312Packages.distutils
    pkgs.python312Packages.numpy
  ];
}
```

</details>

After creating the above file, I was able to build/distribute `visqol` with the following commands:

```sh
# enter the nix environment and build visqol:
nix-shell --run "bazel clean --expunge && bazel --batch build :visqol -c opt"
# the produced binary references (via ldd) lots of /nix/store.... paths: rewrite those so that the binary is executable outside a Nix environment:
cp bazel-bin/visqol bazel-bin/visqol.backup
sudo patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 bazel-bin/visqol
sudo patchelf --remove-rpath bazel-bin/visqol
# Now (YMMV -- use at your own risk), the visqol binary can be copied to other systems and run
```

**Comment by nschimme** [comment]
After many hours of headache, this works on noble:

```
sudo apt-get update && sudo apt-get install -y build-essential curl gnupg python3-numpy

sudo curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
sudo chmod +x /usr/local/bin/bazel
bazel --version

export PYTHON_BIN_PATH=/usr/bin/python3
export PYTHON_LIB_PATH=/usr/lib/python3/dist-packages

git clone https://github.com/google/visqol.git
cd visqol

# 1. First, perform the fetch with the experimental flag.
# This downloads the dependencies into the cache.
bazel fetch --experimental_repo_remote_exec :visqol

# 2. Now that the files are downloaded, find and patch spectrogram.cc
TFLITE_FILE=$(find $(bazel info output_base)/external -name spectrogram.cc | grep "internal/spectrogram.cc" | head -n 1)

if [ -n "$TFLITE_FILE" ]; then
    echo "Patching $TFLITE_FILE..."
    # Add the missing header required for GCC 11+
    sed -i '1i #include <cstdint>' "$TFLITE_FILE"
else
    echo "Error: spectrogram.cc not found. Check if the fetch step failed."
fi

# 3. Finally, run the build
bazel build :visqol -c opt --copt=-w --experimental_repo_remote_exec
```

Consider using Docker for your use case instead. You can see how I did it here: https://github.com/nschimme/faac-benchmark/blob/master/Dockerfile.visqol
